name: izlyclient
description: A Dart library for interacting with the Izly platform, allowing you to perform various operations such as retrieving balances, generating QR codes, recharging accounts, and more.
version: 1.0.9
repository: https://github.com/onyx-lyon1/onyx/tree/main/packages/izlyclient

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^4.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^5.0.2

dependencies:
  requests_plus: ^4.8.3
  html: ^0.15.4
  hive: ^2.2.3
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
  beautiful_soup_dart: ^0.3.0
  intl: ^0.18.1
