name: onyx
description: ade, tomuss Mail pour lyon1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.8+49

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0-pre
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  animations: ^2.0.8
  auto_size_text: ^3.0.0
  copy_with_extension: ^5.0.4
  responsive_sizer: 3.2.0
  desktop_window: ^0.4.0
  # internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_localized_locales: ^2.0.5

  #agenda
  lyon1agendaclient: ^1.0.8

  #agenda_config
  qr_code_dart_scan: ^0.7.3
  permission_handler: ^11.0.1
  encrypt: ^5.0.3

  #izly
  izlyclient: ^1.0.7

  #mail
  lyon1mailclient: ^1.0.8
  webview_flutter: ^4.4.1
  file_picker: ^6.0.0
  open_filex: ^4.3.4
  flutter_file_dialog: ^3.0.2
  flutter_quill: ^9.0.5
  vsc_quill_delta_to_html: ^1.0.3
  enough_mail: ^2.1.3
  keyboard_attachable: ^2.2.0

  #cas
  lyon1casclient: ^1.0.7

  #tomuss
  lyon1tomussclient: ^1.0.8
  screenshot: ^2.1.0
  share_plus: ^7.2.1

  #map
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  flutter_map: ^6.1.0
  flutter_map_location_marker: ^8.0.2
  flutter_map_animations: ^0.5.3
  flutter_map_marker_cluster: ^1.3.4
  flutter_map_tile_caching: ^9.0.0-dev.3
  requests_plus: ^4.8.5

  #authentication
  connectivity_plus: ^5.0.1

  #notifications
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.1.0

  #settings
  drag_and_drop_lists:
    git: https://github.com/onyx-lyon1/DragAndDropLists.git
  equatable: ^2.0.5
  biometric_storage: ^5.0.0+4
  logger: ^2.0.2+1
  json_theme: ^6.3.1

  #colloscope
  polytechcolloscopeclient: ^1.0.9
  diacritic: ^0.1.5

  #examen
  lyon1examenclient: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  copy_with_extension_gen: ^5.0.4
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.9

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/agenda_ids.json.enc
    - assets/batiment_lyon1.json
    - assets/discord_Logo.png
    - assets/icon_transparent.png
    - assets/iv.txt
    - assets/key.txt
    - assets/izly.png
    - assets/izly_mock_qr-code.png
    - assets/key.txt
    - assets/graph.json.gz
    - assets/colloscope_ids.enc
    - assets/stop_words/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
