name: onyx
description: ade, tomuss Mail pour lyon1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.5+46

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  modal_bottom_sheet: ^3.0.0-pre
  flutter_bloc: ^8.1.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  animations: ^2.0.8
  auto_size_text: ^3.0.0
  copy_with_extension: ^5.0.4
  responsive_sizer: 3.2.0
  desktop_window: ^0.4.0
  #agenda
  lyon1agendaclient: ^1.0.6

  #agenda_config
  qr_code_dart_scan: ^0.7.2
  permission_handler: ^11.0.1
  encrypt: ^5.0.3

  #izly
  izlyclient: ^1.0.6

  #mail
  lyon1mailclient: ^1.0.6
  webview_flutter: ^4.4.1
  file_picker: ^5.5.0
  open_filex: ^4.3.4
  flutter_file_dialog: ^3.0.2
  flutter_quill: ^7.4.9
  vsc_quill_delta_to_html: ^1.0.3
  enough_mail: ^2.1.2

  #cas
  lyon1casclient: ^1.0.6

  #tomuss
  lyon1tomussclient: ^1.0.6
  screenshot: ^2.1.0
  share_plus: ^7.1.0

  #map
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.0
  flutter_map: ^5.0.0
  flutter_map_location_marker: ^7.0.5
  flutter_map_animations: ^0.4.1
  flutter_map_marker_cluster: ^1.2.0
  requests_plus: ^4.8.3


  #authentication
  connectivity_plus: ^5.0.0

  #notifications
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.1.0

  #settings
  drag_and_drop_lists:
    git: https://github.com/onyx-lyon1/DragAndDropLists.git
  equatable: ^2.0.5
  biometric_storage: ^5.0.0+4
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  copy_with_extension_gen: ^5.0.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map/
    - assets/map/14/
    - assets/map/14/8412/
    - assets/map/14/8413/
    - assets/map/14/8414/
    - assets/map/15/
    - assets/map/15/16825/
    - assets/map/15/16826/
    - assets/map/15/16827/
    - assets/map/15/16828/
    - assets/map/15/16829/
    - assets/map/16/
    - assets/map/16/33651/
    - assets/map/16/33652/
    - assets/map/16/33653/
    - assets/map/16/33654/
    - assets/map/16/33655/
    - assets/map/16/33656/
    - assets/map/16/33657/
    - assets/map/16/33658/
    - assets/map/17/
    - assets/map/17/67303/
    - assets/map/17/67304/
    - assets/map/17/67305/
    - assets/map/17/67306/
    - assets/map/17/67307/
    - assets/map/17/67308/
    - assets/map/17/67309/
    - assets/map/17/67310/
    - assets/map/17/67311/
    - assets/map/17/67312/
    - assets/map/17/67313/
    - assets/map/17/67314/
    - assets/map/17/67315/
    - assets/map/17/67316/
    - assets/map/18/
    - assets/map/18/134606/
    - assets/map/18/134607/
    - assets/map/18/134608/
    - assets/map/18/134609/
    - assets/map/18/134610/
    - assets/map/18/134611/
    - assets/map/18/134612/
    - assets/map/18/134613/
    - assets/map/18/134614/
    - assets/map/18/134615/
    - assets/map/18/134616/
    - assets/map/18/134617/
    - assets/map/18/134618/
    - assets/map/18/134619/
    - assets/map/18/134620/
    - assets/map/18/134621/
    - assets/map/18/134622/
    - assets/map/18/134623/
    - assets/map/18/134624/
    - assets/map/18/134625/
    - assets/map/18/134626/
    - assets/map/18/134627/
    - assets/map/18/134628/
    - assets/map/18/134629/
    - assets/map/18/134630/
    - assets/map/18/134631/
    - assets/map/18/134632/
    - assets/map/19/
    - assets/map/19/269213/
    - assets/map/19/269214/
    - assets/map/19/269215/
    - assets/map/19/269216/
    - assets/map/19/269217/
    - assets/map/19/269218/
    - assets/map/19/269219/
    - assets/map/19/269220/
    - assets/map/19/269221/
    - assets/map/19/269222/
    - assets/map/19/269223/
    - assets/map/19/269224/
    - assets/map/19/269225/
    - assets/map/19/269226/
    - assets/map/19/269227/
    - assets/map/19/269228/
    - assets/map/19/269229/
    - assets/map/19/269230/
    - assets/map/19/269231/
    - assets/map/19/269232/
    - assets/map/19/269233/
    - assets/map/19/269234/
    - assets/map/19/269235/
    - assets/map/19/269236/
    - assets/map/19/269237/
    - assets/map/19/269238/
    - assets/map/19/269239/
    - assets/map/19/269240/
    - assets/map/19/269241/
    - assets/map/19/269242/
    - assets/map/19/269243/
    - assets/map/19/269244/
    - assets/map/19/269245/
    - assets/map/19/269246/
    - assets/map/19/269247/
    - assets/map/19/269248/
    - assets/map/19/269249/
    - assets/map/19/269250/
    - assets/map/19/269251/
    - assets/map/19/269252/
    - assets/map/19/269253/
    - assets/map/19/269254/
    - assets/map/19/269255/
    - assets/map/19/269256/
    - assets/map/19/269257/
    - assets/map/19/269258/
    - assets/map/19/269259/
    - assets/map/19/269260/
    - assets/map/19/269261/
    - assets/map/19/269262/
    - assets/map/19/269263/
    - assets/map/19/269264/
    - assets/map/19/269265/
    - assets/screenshots/


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
