name: lyon1agendaclient
description: A Dart library for retrieving Lyon 1 University agendas using Lyon1CasClient for authentication.
repository: https://github.com/onyx-lyon1/onyx/tree/main/packages/lyon1agendaclient
version: 1.0.10
environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^5.1.1
  test: ^1.20.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^5.0.2

dependencies:
  requests_plus: ^4.8.3
  lyon1casclient: ^1.0.2
  icalendar_parser: ^2.0.0
  dotenv: ^4.1.0
  hive: ^2.2.3
  equatable: ^2.0.5
  copy_with_extension: ^5.0.4
