name: lyon1tomussclient
description: A Dart library for interacting with Tomuss, Lyon 1 University's academic platform, using Lyon1CasClient for authentication.
version: 1.0.8
repository: https://github.com/onyx-lyon1/onxy/packages/lyon1tomussclient

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  dotenv: ^4.0.1
  lints: ^2.0.0
  test: ^1.20.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  copy_with_extension_gen: ^5.0.2
dependencies:
  beautiful_soup_dart: ^0.3.0
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  hive: ^2.2.3
  requests_plus: ^4.8.5
  lyon1casclient: ^1.0.6

#dependency_overrides:
#  requests:
#    path: /home/eymeric/tmp/requests
