name: lyon1casclient
description: A Dart library that provides authentication with the CAS (Central Authentication Service) system of Lyon 1 University (https://cas.univ-lyon1.fr).
version: 1.0.7
repository: https://github.com/onyx-lyon1/onxy/tree/main/packages/lyon1casclient

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  hive: ^2.2.3
  requests_plus: ^4.8.5
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.8
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  copy_with_extension_gen: ^5.0.4
  dotenv: ^4.2.0
