name: lyon1examenclient
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/onyx-lyon1/onyx/tree/main/packages/lyon1examenclient

environment:
  sdk: ^3.2.3

dependencies:
  beautiful_soup_dart: ^0.3.0
  dart_mappable: ^4.2.0
  lyon1casclient: ^1.0.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  dart_mappable_builder: ^4.2.0
  build_runner: ^2.4.7
  dotenv: ^4.2.0
